### ISSUE TITLE
Public access to builder base image

### ISSUE THREAD

**Issue by petiepooo** [datmanslo/ubuntu-snort3#1]
It looks like the public doesn't have access to your ubuntu-snort3-dev image (or it doesn't exist).  When running build.sh, even after providing docker hub credentials, I get:

> Sending build context to Docker daemon  4.096kB
Step 1/16 : ARG BUILDER_BASE=datmanslo/ubuntu-snort3-dev
Step 2/16 : ARG BUILDER_TAG=20.04
Step 3/16 : ARG RUNTIME_BASE=ubuntu
Step 4/16 : ARG RUNTIME_TAG=20.04
Step 5/16 : FROM ${BUILDER_BASE}:${BUILDER_TAG} as builder
pull access denied for datmanslo/ubuntu-snort3-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by datmanslo** [comment]
Thank you. Fixed. No more dependency.
