### ISSUE TITLE
'jq' requirement

### ISSUE THREAD

**Issue by petiepooo** [datmanslo/ubuntu-snort3#2]
On a base build of Ubuntu 20.04 LTS server, jq is not installed, yet build.sh line 23 calls for it, resulting in the following error:

> Checking prerequisites: Docker, Curl
> 
> Verifying docker
docker is installed. Moving on...
> 
> Verifying curl
curl is installed. Moving on...
> 
> ./build.sh: 23: jq: not found

**Comment by datmanslo** [comment]
Thanks you. Fixed
